version: '3'

services:
  nginx-proxy:
    image: nginx:stable-alpine
#    labels:
#      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-proxy # Nom du conteneur principal nginx. Utilisé plus bas par les autres conteneurs.
    restart: always
    ports:
      - "80:80"
      - "443:443"

#    environment:
      SSL_POLICY: Mozilla-Intermediate
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/certs:/etc/nginx/certs:ro
    logging:
      driver: ${NGINX_WEB_LOG_DRIVER:-json-file}
      options:
        max-size: 4m
        max-file: 10

  docker-gen-auto:
    image: jwilder/docker-gen:latest
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: docker-gen-auto
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: ${NGINX_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: 2m
        max-file: 10

  letsencrypt-auto:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: letsencrypt-auto
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - ./data/certs:/etc/nginx/certs:rw
      - ./data/acme.sh:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: docker-gen-auto
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: tech@alliage-maintenance.com
    logging:
      driver: ${NGINX_LETSENCRYPT_LOG_DRIVER:-json-file}
      options:
        max-size: 2m
        max-file: 10

networks:
  default:
    external:
      name: proxy # Nom du réseau qu'il faudra ajouter dans les applications situées derrière le proxy
