FROM php:8.2-fpm-buster

# install FR locales
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get clean; \
	apt-get update; \
	apt-get install -y locales;
RUN echo "fr_FR.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen fr_FR.UTF-8 && \
    update-locale fr_FR.UTF-8
ENV LC_ALL fr_FR.UTF-8

# Install networks utils
RUN apt-get install -y iputils-ping;

# install the PHP extensions we need
RUN apt-get update || apt-get update; # FIX the apt-get install error!
# Install required packages
RUN apt-get install -y gcc libjpeg-dev libpng-dev libc-client-dev libkrb5-dev libldap2-dev libxml2-dev libzip-dev libfreetype6-dev
# KERBEROS / IMAP
RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl
# GD
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
# LDAP
#RUN docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/
# OTHER EXTENSIONS
#RUN docker-php-ext-install exif gd imap ldap
#RUN docker-php-ext-install pcntl soap
#RUN docker-php-ext-install zip opcache mysqli pdo_mysql
# XDEBUG
#RUN pecl install -o -f xdebug
#RUN docker-php-ext-enable xdebug

# MEMCACHED
RUN apt-get install -y libmemcached-dev;
RUN curl -L -o /tmp/memcached.tar.gz "https://github.com/php-memcached-dev/php-memcached/archive/v3.1.5.tar.gz" \
  && mkdir -p memcached \
  && tar -C memcached -zxvf /tmp/memcached.tar.gz --strip 1 \
  && ( \
    cd memcached \
    && phpize \
    && ./configure \
    && make -j$(nproc) \
    && make install \
  ) \
  && rm -r memcached \
  && rm /tmp/memcached.tar.gz \
  && docker-php-ext-enable memcached

# SSH2 package
#RUN set -ex; \
#        BUILD_PACKAGES="libssh2-1-dev libssh2-1"; \
#	apt-get update; \
#	apt-get install -y $BUILD_PACKAGES; \
#        pecl install -o -f ssh2-1.2 \
#        && docker-php-ext-enable ssh2 \
#        && rm -rf /tmp/pear;


# Microsoft SQL Server Prerequisites
ENV ACCEPT_EULA=Y
RUN apt-get install -y libonig-dev gnupg \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list \
        > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get install -y --no-install-recommends \
        apt-transport-https \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
        unixodbc-dev \
        msodbcsql17;
# MSSQL PHP Driver & plugin
RUN docker-php-ext-install mbstring pdo pdo_mysql \
    && pecl install sqlsrv pdo_sqlsrv  \
    && docker-php-ext-enable sqlsrv pdo_sqlsrv

# MSMTP
RUN apt-get install -y msmtp
COPY msmtprc /etc/msmtprc
RUN chown root:msmtp /etc/msmtprc
RUN chmod 640 /etc/msmtprc
RUN touch /var/log/msmtp.log; chmod 660 /var/log/msmtp.log

# https://github.com/mlocati/docker-php-extension-installer
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions
RUN install-php-extensions intl xdebug exif gd imap ldap pcntl soap zip opcache mysqli pdo_mysql

# NETTOYAGE
RUN set -ex; \
        apt-get remove -y gcc g++ libpng-dev libjpeg-dev libfreetype6-dev \
        && rm -rf /tmp/pear;

# Clean setup
RUN rm -rf /var/lib/apt/lists/*

# SET php.ini-developpement
RUN ln -s /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini;

# COPY CUSTOM CONFIGS
ADD php.ini /usr/local/etc/php/conf.d/user-php.ini
ADD logs-8.2.ini /usr/local/etc/php/conf.d/logs.ini
ADD uploads.ini /usr/local/etc/php/conf.d/uploads.ini
ADD xdebug-8.0.ini /usr/local/etc/php/conf.d/xdebug.ini
ADD opcache.ini /usr/local/etc/php/conf.d/opcache.ini
ADD php-mail.ini /usr/local/etc/php/conf.d/php-mail.ini

RUN sed -i -e "s/listen = 127.0.0.1:9000/listen = 9000/g" /usr/local/etc/php-fpm.d/www.conf;

# START PHP-FPM
CMD ["php-fpm"]
EXPOSE 9000